language: go

go:
    - 1.2
    - tip

services:
    - redis-server
    - memcached

env:
    - TEST_REDIS_ADDRESSES=localhost:6379 TEST_REDIS_WAIT_DURATION=2s
    - TEST_MEMCACHED_ADDRESSES=localhost:11211 TEST_MEMCACHED_WAIT_DURATION=2s

before_script:

script:
    - go test -v ./...
